name: "Task 3: Build and Deploy App"

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Додає кнопку "Run workflow" вручну для тестів

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout App Code
        uses: actions/checkout@v4
        with:
          repository: 'YulianSalo/devops-exam-pt2'
          fetch-depth: 0 # ОБОВ'ЯЗКОВО для роботи з гілками

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # ВИКОРИСТОВУЄМО ТВОЇ РЕАЛЬНІ НАЗВИ СЕКРЕТІВ
          username: ${{ secrets.DOCKERHUB_KURASEVYCH }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Build and Push DEV (develop branch)
        run: |
          git checkout develop
          docker build -t kurasevych/devops-app:develop .
          docker push kurasevych/devops-app:develop

      - name: Build and Push RELEASE (tag 1.0.0)
        run: |
          git checkout 1.0.0
          docker build -t kurasevych/devops-app:1.0.0 .
          docker push kurasevych/devops-app:1.0.0
