name: "Cloud Deployment CI/CD"

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    name: "Infrastructure (Terraform)"
    runs-on: ubuntu-latest
    outputs:
      target_ip: ${{ steps.out.outputs.ip }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: TF Init
        run: terraform init -reconfigure -backend-config="access_key=${{ secrets.SPACES_ACCESS_ID }}" -backend-config="secret_key=${{ secrets.SPACES_SECRET_KEY }}"
        working-directory: ./terraform

      - name: TF Plan
        run: >
          terraform plan 
          -var="do_token=${{ secrets.DO_TOKEN }}" 
          -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" 
          -var="spaces_access_id=${{ secrets.SPACES_ACCESS_ID }}" 
          -var="spaces_secret_key=${{ secrets.SPACES_SECRET_KEY }}"
        working-directory: ./terraform

      - name: TF Apply
        run: >
          terraform apply -auto-approve 
          -var="do_token=${{ secrets.DO_TOKEN }}" 
          -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" 
          -var="spaces_access_id=${{ secrets.SPACES_ACCESS_ID }}" 
          -var="spaces_secret_key=${{ secrets.SPACES_SECRET_KEY }}"
        working-directory: ./terraform

      - name: Export IP
        id: out
        run: echo "ip=$(terraform output -raw droplet_ip)" >> $GITHUB_OUTPUT
        working-directory: ./terraform

  ansible:
    name: "Software (Ansible)"
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Чекаємо 30 секунд, щоб SSH на сервері встиг піднятися
          sleep 30
          ssh-keyscan -H ${{ needs.terraform.outputs.target_ip }} >> ~/.ssh/known_hosts

      - name: Ansible Install (Kubernetes & Minikube)
        run: |
          ansible-playbook -i '${{ needs.terraform.outputs.target_ip }},' -u root --private-key ~/.ssh/id_rsa ansible/playbook.yml

      - name: Setup Minikube Proxy
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@${{ needs.terraform.outputs.target_ip }} "kubectl proxy --address='0.0.0.0' --accept-hosts='.*' > /dev/null 2>&1 &"
